main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Projects
    url: '#projects'
    weight: 30
  - name: Publications
    url: '#featured'
    weight: 50
  - name: Contact
    url: '#contact'
    weight: 60
  - name: CV
    url: uploads/resume.pdf
    weight: 70
